export const PAGE_TITLES = {
  HOME: 'Головна - КСУ',
  ABITURIENT: 'Абітурієнту - КСУ',
  BAKALAVR: 'Бакалаврат - КСУ',
  MAGISTR: 'Магістратура - КСУ',
  PHD: 'PhD - КСУ',
  LABORATORIES: 'Лабораторії - КСУ',
  STUDLIFE: ' Студентьске життя - КСУ',
  DOCS: 'Документи - КСУ',
  SCIENCE: 'Наука - КСУ',
  HISTORY: 'Історія кафедри - КСУ',
  NEWS: 'Новини - КСУ',
  KAFEDRA: 'Співробітники - КСУ',
  REVIEWS: 'Відгуки - КСУ',
  CONTACTS: 'Контакти - КСУ',
  FEEDBACK: "Зворотній Зв'язок - КСУ",
};
